#!/bin/bash
scriptdir="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
. "$scriptdir/ogenc-context1"

$scriptdir/ogenc-compilers update || exit 1

[ -z $default_generator ] && default_generator="${CXXGEN}"
[ -z $default_generator ] && default_generator=$(cat ${default_generator_f} 2>/dev/null )
