#!/bin/bash

scriptdir="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
[ -z $VERBOSE ] && VERBOSE=0
VERBOSE=$VERBOSE $scriptdir/ogenc-generator warnings
VERBOSE=$VERBOSE $scriptdir/ogenc-generator optimize
VERBOSE=$VERBOSE $scriptdir/ogenc-splitter warnings
VERBOSE=$VERBOSE $scriptdir/ogenc-splitter optimize
VERBOSE=$VERBOSE $scriptdir/ogenc-cmake warnings
VERBOSE=$VERBOSE $scriptdir/ogenc-cmake optimize
