#!/bin/bash

scriptdir="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
. "$scriptdir/ogenc-context2"
[ -z $VERBOSE ] && VERBOSE=0

while IFS="" read -r target_line
do
  target_comp=$(echo $target_line | awk '{print $3}')
  VERBOSE=$VERBOSE $scriptdir/ogenc-generator warnings ${target_comp}
  VERBOSE=$VERBOSE $scriptdir/ogenc-generator optimize ${target_comp}
done < "${available_compilers_f}"

VERBOSE=$VERBOSE $scriptdir/ogenc-splitter warnings
VERBOSE=$VERBOSE $scriptdir/ogenc-splitter optimize
VERBOSE=$VERBOSE $scriptdir/ogenc-cmake warnings
VERBOSE=$VERBOSE $scriptdir/ogenc-cmake optimize
