#!/bin/bash
export LANG=en_US.UTF-8

scriptdir="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
PATH="$PATH:$scriptdir"
scriptname=$(basename -- "${BASH_SOURCE[0]}")
config_path="${scriptdir}/.config"
cache_path="${scriptdir}/.cache"

command=list
current_compiler=${CXX}
[ -z $current_compiler ] && bash -c "g++ --version" >/dev/null 2>&1 && current_compiler=g++
[ -z $current_compiler ] && bash -c "clang++ --version" >/dev/null 2>&1 && current_compiler=clang++
compilers_list_f="${config_path}/compilers.txt"
available_compilers_f="${cache_path}/available_compilers.txt"
current_generator_f="${cache_path}/generator.txt"
[ -z $current_generator ] && current_generator="${CXXGEN}"
[ -z $current_generator ] && current_generator=$(cat ${current_generator_f} 2>/dev/null )

generator_options="-Wall -Wextra -Wpedantic -Wformat --pedantic-errors"

function log()
{
  [ -z $VERBOSE ] && return
  (( $1 <= $VERBOSE )) && echo "$2"
}
